from pathlib import Path
import base64,json,subprocess
root=Path(__file__).resolve().parents[1]
subprocess.run([str(root/'preview/vendor/node_modules/.bin/esbuild'),str(root/'preview/vendor/envelope_viewer.js'),'--bundle','--minify','--format=esm',f'--outfile={root}/preview/envelope.bundle.js'],check=True)
data=[]
for name in ['Sembang_Cream_Envelope','Sembang_Wax_Seal']:
 data.append(dict(name=name,base64=base64.b64encode((root/'envelope'/f'{name}.glb').read_bytes()).decode()))
html='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sembang — Cream envelope & wax seal</title><style>
*{box-sizing:border-box}body{margin:0;background:#f5f0e7;color:#392d31;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif}header{padding:30px 4vw;display:flex;justify-content:space-between;border-bottom:1px solid #dfd7cb;font-size:11px;letter-spacing:2px;font-weight:650}header span:last-child{color:#9d6c7c}main{display:grid;grid-template-columns:300px 1fr;gap:30px;padding:44px 4vw 24px}aside{padding-top:26px}.eyebrow{font-size:10px;letter-spacing:2px;color:#b73d63;font-weight:700}h1{font-family:Georgia,serif;font-weight:400;font-size:49px;line-height:1.04;letter-spacing:-2px;margin:20px 0 22px}p{font-size:14px;line-height:1.8;color:#897780;margin:0 0 23px}.swatches{display:flex;gap:16px;font-size:11px;color:#887780;margin-bottom:35px}.swatches span{display:flex;align-items:center;gap:7px}.swatches i{width:14px;height:14px;border-radius:50%;border:1px solid #47363818}button{font:inherit;cursor:pointer;border:1px solid #d7ccc7;border-radius:8px;background:transparent;padding:10px 14px;color:inherit}button:hover{border-color:#b43b60}.download{display:block;width:100%;text-align:left;font-size:12px;margin:10px 0;padding:14px 16px}.download.primary{background:#ac3658;color:#fff;border-color:#ac3658}.tiny{font-size:11px;line-height:1.7;color:#a28e97}.viewer{min-width:0;border:1px solid #e1d7cf;border-radius:18px;background:#ece3d9;overflow:hidden}.viewerhead{display:flex;justify-content:space-between;align-items:center;padding:19px 23px}.tabs{display:flex;gap:6px}.tabs button{font-size:11px;border:0}.tabs .selected{background:#fff8ed}.object-label{font-size:10px;letter-spacing:1px;color:#937d84}#stage{height:500px;touch-action:none;cursor:grab;background:radial-gradient(ellipse at 50% 44%,#f8f2e6 0%,#ece3d9 78%)}#stage canvas{display:block;width:100%;height:100%}.toolbar{display:flex;gap:7px;justify-content:center;padding:15px 15px 22px}.toolbar button{font-size:11px;padding:9px 12px}.toolbar .active{background:#443239;border-color:#443239;color:#fff}.help{text-align:center;font-size:10px;color:#a28e97;letter-spacing:.3px;padding:0 0 18px}footer{margin:0 4vw;padding:20px 0 25px;border-top:1px solid #dfd7cb;display:flex;justify-content:space-between;font-size:10px;color:#a18c94;line-height:1.8}@media(max-width:900px){main{grid-template-columns:1fr;padding-top:15px}aside{max-width:560px}h1{font-size:38px}.swatches{margin-bottom:18px}#stage{height:400px}.download{display:inline-block;width:auto;margin-right:8px}.object-label{display:none}}@media(max-width:500px){header{font-size:9px}#stage{height:300px}.toolbar{gap:4px}.toolbar button{font-size:10px;padding:8px}footer{display:block}}
</style></head><body><header><span>SEMBANG ENTERTAINMENT</span><span>OBJECT 02 / CORRESPONDENCE</span></header><main><aside><div class="eyebrow">A LITTLE MORE PERSONAL</div><h1>Sealed with<br>Sembang.</h1><p>A cream envelope, folded and finished with raspberry wax. Your original S and star sit in cream on the raised seal.</p><div class="swatches"><span><i style="background:#f7f0d7"></i>Cream paper</span><span><i style="background:#ef4c7a"></i>Raspberry wax</span></div><button class="download primary" data-download="0">Download envelope GLB ↓</button><button class="download" data-download="1">Download wax seal GLB ↓</button><p class="tiny">OBJ + material files are included in the envelope folder. The wax seal is also available as a separate model.</p></aside><section class="viewer"><div class="viewerhead"><div class="tabs"><button data-model="0" class="selected">Envelope</button><button data-model="1">Wax seal</button></div><span id="object-name" class="object-label">The sealed envelope</span></div><div id="stage" aria-label="Interactive envelope and wax seal 3D preview"></div><div class="toolbar"><button data-view="front">Front</button><button data-view="angle" class="active">Perspective</button><button data-view="back">Back</button><button data-view="side">Edge</button><button id="spin">Auto rotate</button></div><div class="help">Drag to turn · Scroll to zoom</div></section></main><footer><span>Original S + star artwork · Soft paper folds · Pressed wax rim</span><span>Self-contained 3D preview / Works offline</span></footer><script id="model-data" type="application/json">__DATA__</script><script type="module">__SCRIPT__</script></body></html>'''
html=html.replace('__DATA__',json.dumps(data)).replace('__SCRIPT__',(root/'preview/envelope.bundle.js').read_text())
(root/'Sembang Envelope Preview.html').write_text(html)
print('Envelope preview built.')
