"""Offline viewer for the clapperboard and clipboard.

Reuses the already-bundled Three.js viewer (preview/envelope.bundle.js) and only
re-frames the camera for these two props, so no Node toolchain is required.
"""
from pathlib import Path
import base64, json
root = Path(__file__).resolve().parents[1]
items = [('Sembang_Clapperboard', 'clapperboard'), ('Sembang_Clipboard', 'clipboard'), ('Sembang_Megaphone', 'megaphone')]
data = [dict(name=n, base64=base64.b64encode((root/folder/f'{n}.glb').read_bytes()).decode()) for n, folder in items]
bundle = (root/'preview/envelope.bundle.js').read_text()
html = '''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sembang — Clapperboard & clipboard</title><style>
*{box-sizing:border-box}body{margin:0;background:#f2f0ee;color:#392d31;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif}header{padding:30px 4vw;display:flex;justify-content:space-between;border-bottom:1px solid #dcd7d3;font-size:11px;letter-spacing:2px;font-weight:650}header span:last-child{color:#9d6c7c}main{display:grid;grid-template-columns:300px 1fr;gap:30px;padding:44px 4vw 24px}aside{padding-top:26px}.eyebrow{font-size:10px;letter-spacing:2px;color:#b73d63;font-weight:700}h1{font-family:Georgia,serif;font-weight:400;font-size:49px;line-height:1.04;letter-spacing:-2px;margin:20px 0 22px}p{font-size:14px;line-height:1.8;color:#7f7479;margin:0 0 23px}.swatches{display:flex;flex-wrap:wrap;gap:10px 16px;font-size:11px;color:#7f7479;margin-bottom:35px}.swatches span{display:flex;align-items:center;gap:7px}.swatches i{width:14px;height:14px;border-radius:50%;border:1px solid #2b262833}button{font:inherit;cursor:pointer;border:1px solid #d3cbc8;border-radius:8px;background:transparent;padding:10px 14px;color:inherit}button:hover{border-color:#b43b60}.download{display:block;width:100%;text-align:left;font-size:12px;margin:10px 0;padding:14px 16px}.download.primary{background:#2b2628;color:#fff;border-color:#2b2628}.tiny{font-size:11px;line-height:1.7;color:#9c9096}.viewer{min-width:0;border:1px solid #dcd5d0;border-radius:18px;background:#e6e1dd;overflow:hidden}.viewerhead{display:flex;justify-content:space-between;align-items:center;padding:19px 23px}.tabs{display:flex;gap:6px}.tabs button{font-size:11px;border:0}.tabs .selected{background:#fbf9f7}.object-label{font-size:10px;letter-spacing:1px;color:#8d8085}#stage{height:540px;touch-action:none;cursor:grab;background:radial-gradient(ellipse at 50% 44%,#faf8f5 0%,#e6e1dd 78%)}#stage canvas{display:block;width:100%;height:100%}.toolbar{display:flex;gap:7px;justify-content:center;padding:15px 15px 22px}.toolbar button{font-size:11px;padding:9px 12px}.toolbar .active{background:#2b2628;border-color:#2b2628;color:#fff}.help{text-align:center;font-size:10px;color:#9c9096;letter-spacing:.3px;padding:0 0 18px}footer{margin:0 4vw;padding:20px 0 25px;border-top:1px solid #dcd7d3;display:flex;justify-content:space-between;font-size:10px;color:#9c9096;line-height:1.8}@media(max-width:900px){main{grid-template-columns:1fr;padding-top:15px}aside{max-width:560px}h1{font-size:38px}.swatches{margin-bottom:18px}#stage{height:420px}.download{display:inline-block;width:auto;margin-right:8px}.object-label{display:none}}@media(max-width:500px){header{font-size:9px}#stage{height:320px}.toolbar{gap:4px}.toolbar button{font-size:10px;padding:8px}footer{display:block}}
</style></head><body><header><span>SEMBANG ENTERTAINMENT</span><span>OBJECTS 05 + 06 + 07 / ON SET</span></header><main><aside><div class="eyebrow">LIGHTS · CAMERA · ANNOUNCE</div><h1>Ready<br>on set.</h1><p>A film clapperboard with a hinged striped arm and lettered slate, and a raspberry clipboard with a cream clip and a loose sheet of paper, and a pistol-grip megaphone carrying the Sembang S.</p><div class="swatches"><span><i style="background:#ef4c7a"></i>Raspberry</span><span><i style="background:#fbfacf"></i>Cream</span><span><i style="background:#f9bfc5"></i>Blush</span><span><i style="background:#d6ab5c"></i>Gold</span></div><button class="download primary" data-download="0">Download clapperboard GLB ↓</button><button class="download" data-download="1">Download clipboard GLB ↓</button><button class="download" data-download="2">Download megaphone GLB ↓</button><p class="tiny">OBJ + material files are in the clapperboard, clipboard and megaphone folders.</p></aside><section class="viewer"><div class="viewerhead"><div class="tabs"><button data-model="0" class="selected">Clapperboard</button><button data-model="1">Clipboard</button><button data-model="2">Megaphone</button></div><span id="object-name" class="object-label">The raspberry clapperboard</span></div><div id="stage" aria-label="Interactive clapperboard and clipboard 3D preview"></div><div class="toolbar"><button data-view="front">Front</button><button data-view="angle" class="active">Perspective</button><button data-view="back">Back</button><button data-view="side">Edge</button><button id="spin">Auto rotate</button></div><div class="help">Drag to turn · Scroll to zoom</div></section></main><footer><span>Rounded, bevelled parts · PBR materials · Lettered slate</span><span>Self-contained 3D preview / Works offline</span></footer><script id="model-data" type="application/json">__DATA__</script><script type="module">__SCRIPT__</script><script type="module">
const names=['The raspberry clapperboard','The raspberry clipboard','The Sembang megaphone'];
const wait=setInterval(()=>{if(!window.modelsReady)return;clearInterval(wait);
 const {camera,controls}=window.envelopeViewer;const base=window.setView;
 const frame=()=>{const i=Number(document.querySelector('[data-model].selected').dataset.model);
  camera.position.set(0,0,[8.9,10.2,11.2][i]);controls.target.set(0,[.06,.15,-.4][i],0);controls.minDistance=4;controls.maxDistance=20;controls.update();
  document.querySelector('#object-name').textContent=names[i];};
 window.setView=m=>{base(m);frame();const i=Number(document.querySelector('[data-model].selected').dataset.model);if(i===2&&m==='angle')window.envelopeViewer.models[2].rotation.set(.1,-.62,0);};window.setView('angle');
 const q=new URLSearchParams(location.hash.slice(1));if(q.has('m'))window.selectModel(Number(q.get('m')));if(q.has('v'))window.setView(q.get('v'));},30);
</script></body></html>'''
html = html.replace('__DATA__', json.dumps(data)).replace('__SCRIPT__', bundle)
(root/'Sembang Studio Props Preview.html').write_text(html, encoding='utf-8')
print('Props preview built.')
